### ISSUE TITLE
请问这几句代码怎么就找到歌曲信息了呢？我用浏览器打开任何歌曲找不到信息

### ISSUE THREAD

**Issue by jiangliang1987** [gh351135612/BmobMusic#1]
String url = “http://music.163.com/#/discover/toplist?id=19723756”
Document  doc = Jsoup.connect(url).userAgent("Mozilla").get();
Elements e = doc.select("textarea[style=display:none;]");
String result = `e.get(0).text();

望解惑！ 难道Jsoup除了解析html还会做其他额外的事？

**Comment by gh351135612** [comment]
这个链接是我通过分析网易的请求得到的，可能在你用的时候接口发生了改变，所以看不到任何信息。

**Comment by jiangliang1987** [comment]
回复这么快！ 找到原因了，我用谷歌浏览器右键查看代码的时候，有查看框架源代码和查看网页源代码两个选项， 选网页源代码查看不到框架里面的内容信息！

**Comment by gh351135612** [comment]
你有没有看到这行代码？doc.select("textarea[style=display:none;]  我要的信息在html中是隐藏的属性，所以用浏览器看不到

**Comment by jiangliang1987** [comment]
选择查看框架源代码，可以看到。里面是一个近100首歌曲信息的JSON数据。

**Comment by jiangliang1987** [comment]
请问有直接搜索单首歌曲获得mp3链接的办法吗

**Comment by gh351135612** [comment]
你可以去网上搜一下别人第三方写的歌曲搜索网站，然后模拟请求得到数据，就像我歌词的搜索与下载一样。
